select UPPER(REPLACE(TRIM(CLAIM_NO), '-', '')) as claim_id,
	POLICY_NO as policy_id,
	CLAIM_DATE as claim_date,
	MONTHS_AS_CUSTOMER,
	INJURY,
	PROPERTY,
	VEHICLE,
	TOTAL as claim_amount,
	COLLISION_TYPE,
	NUMBER_OF_VEHICLES_INVOLVED,
	AGE,
	INSURED_RELATIONSHIP,
	LICENSE_ISSUE_DATE,
	DATE as loss_date,
	HOUR,
	TYPE,
	SEVERITY as claim_severity,
	NUMBER_OF_WITNESSES,
	SUSPICIOUS_ACTIVITY,
    current_timestamp as dbt_updated_at 
    from {{source('landing','claims')}} 
