select POLICY_NO as policy_id,
    CAST(ROUND(CUST_ID, 0) AS INT) AS customer_id,
	POLICYTYPE,
	POL_ISSUE_DATE,POL_EFF_DATE,
	POL_EXPIRY_DATE,MAKE,MODEL,MODEL_YEAR,
	CHASSIS_NO,USE_OF_VEHICLE,
	PRODUCT,SUM_INSURED,PREMIUM,
	DEDUCTABLE from {{source('landing','policies')}}